#cloud-config
users:
  - name: user
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3BQiBkJnvWpT4ScTOrgpUR7bhqMT79EwVRzbx32pnr user@user-ubuntu-pi
packages:
  - fail2ban
  - ufw
  - iptables
  - openvpn
  - wireguard
  - qrencode
package_update: true
package_upgrade: true
write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      Port 2222
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      MaxAuthTries 2
      AllowTcpForwarding no
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      AllowUsers user
  - path: /etc/wireguard/wg0.conf
    content: |
      [Interface]
      Address = 10.8.0.1/24
      ListenPort = 51820
      PrivateKey = <SERVER_PRIVATE_KEY>

      # NAT aktivieren
      PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      [Peer]
      PublicKey = <CLIENT_PUBLIC_KEY>
      AllowedIPs = 10.8.0.2/32
  - path: /home/user/client_wg.conf
    content: |
      [Interface]
      PrivateKey = <CLIENT_PRIVATE_KEY>
      Address = 10.8.0.2/32
      DNS = 9.9.9.9

      [Peer]
      PublicKey = <SERVER_PUBLIC_KEY>
      Endpoint = <SERVER_PUBLIC_IP>:51820
      AllowedIPs = 0.0.0.0/0
      PersistentKeepalive = 25
runcmd:
  - printf "[sshd]\nenabled = true\nport = ssh, 2222\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow 2222
  - ufw allow 51820/udp
  - ufw enable
  - umask 077
  - wg genkey | tee /etc/wireguard/server.key | wg pubkey > /etc/wireguard/server.pub
  - wg genkey | tee /home/user/client1.key | wg pubkey > /home/user/client1.pub
  - chown user:user /home/user/client1.key
  - chown user:user /home/user/client1.pub
  - sed -i "s|<SERVER_PRIVATE_KEY>|$(cat /etc/wireguard/server.key)|" /etc/wireguard/wg0.conf
  - sed -i "s|<CLIENT_PUBLIC_KEY>|$(cat /home/user/client1.pub)|" /etc/wireguard/wg0.conf
  - sed -i "s|eth0|$(ip route get 1.1.1.1 | awk '{print $5}')|g" /etc/wireguard/wg0.conf
  - sed -i "s|<CLIENT_PRIVATE_KEY>|$(cat /home/user/client1.key)|" /home/user/client_wg.conf
  - sed -i "s|<SERVER_PUBLIC_KEY>|$(cat /etc/wireguard/server.pub)|" /home/user/client_wg.conf
  - sed -i "s|<SERVER_PUBLIC_IP>|$(ip route get 1.1.1.1 | awk '{print $7}')|" /home/user/client_wg.conf
  - chmod 600 /etc/wireguard/wg0.conf
  - echo "net.ipv4.ip_forward=1" | tee /etc/sysctl.d/99-wireguard.conf
  - sysctl --system
  - sudo systemctl enable wg-quick@wg0
  - reboot
